[[main]]
  identifier = "Docs"
  name = "Documentation"
  url = "documentation"
  weight = 1

[[main]]
  identifier = "Proposals"
  name = "Proposals"
  url = "proposals"
  weight = 2

[[main]]
  identifier = "Releases"
  name = "Releases"
  url = "releases"
  weight = 3

# [[main]]
#   identifier = "Blog"
#   name = "Blog"
#   url = "blog"
#   weight = 3
